//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableUsers
    {
        public int UserId { get; set; }
        public string UserSurname { get; set; }
        public string UserName { get; set; }
        public string UserPatronymic { get; set; }
        public System.DateTime UserBirthday { get; set; }
        public int UserRole { get; set; }
        public string UserPhone { get; set; }
        public string UserLogin { get; set; }
        public int UserPassword { get; set; }
        public string UserPhoto { get; set; }
    
        public virtual TableRoles TableRoles { get; set; }
    }
}
